#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
if [ $# -le 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	path="$1"
	ip="$2"
	user="$3"
	pkey_path="$4"
	scp  -o StrictHostKeyChecking=no -i "$pkey_path" "$path" "$user"@"$ip":~/
fi
