#!/usr/bin/env bash
# a bash script to intall nginx on the server
sudo apt update
sudo apt install nginx -y nginx
echo 'server {
    listen 80;
    server_name _;
    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}' | sudo tee /etc/nginx/sites-available/default > /dev/null
sudo service nginx restart
