#!/usr/bin/env bash
# a bash script to intall nginx on the server
sudo apt -y update
sudo apt -y install nginx
echo "server {
    listen 80;
    server_name _;
    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null
new="location = /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"
sed -i '/^}$/i '"$new" /etc/nginx/sites-available/default
sudo service nginx restart
