#!/usr/bin/env bash
# a bash script to make redirect in nginx config file
sudo apt -y update
sudo apt -y install nginx
new_string="server_name _;\n\trewrite ^/redirect_me https://www.google.co.uk/ permanent;"
sudo sed -i "s|server_name _;|${new_string}|g" /etc/nginx/sites-enabled/default
sudo service nginx restart
