#!/usr/bin/env bash
# a bash script to intall nginx on the server
sudo apt -y update
sudo apt -y install nginx
sudo service nginx start
sudo sed -i '/^}$/i \ \n\tlocation=\/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default
sudo service nginx restart
