#!/usr/bin/env bash
# a bash script to intall nginx on the server
header_name="X-Served-By"
header_value="$HOSTNAME"
sudo apt -y update
sudo apt -y install nginx
echo "<h1>Hello World!</h1>" >> /var/www/html/index.html
sudo sed -i "/server_name _;/a\        add_header "$header_name" "$header_value";" /etc/nginx/sites-enabled/default
sudo service nginx restart
